apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 5000
          env:
            - name: DB_URL
              value: mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@mongodb:27017/{{ .Values.mongodb.database }}?authSource=admin
            - name: PORT
              value: "5000"