frontend:
  image: anandu4879/codestep-frontend:v11
  apiUrl: http://backend:5000/api

backend:
  image: anandu4879/codestep-backend:v1
  port: 5000

mongodb:
  image: mongo:7
  port: 27017
  username: admin
  password: changeme
  database: codestep
  storage: 1Gi
